title: AP CSA Blog 
description: ""
owner_name: Aashray
github_username: KinetekEnergy
github_repo: "studentCSA" 
baseurl: "/studentCSA"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/KinetekEnergy"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 

# SWITCH TO ME IF NEEDED
# remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  # - README4YML.md
